package org.oldbox.clippy.frames;

import org.oldbox.clippy.ClippyContext;

import javax.swing.*;
import java.awt.*;
import java.security.InvalidParameterException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class AddCategoryFrame extends JFrame {
    private JTextField categoryName;
    private JButton addButton;
    private JPanel panel;
    private JComboBox colorPicker;

    private static final Map<String, Color> colors;
    static {
        Map<String, Color> c = new HashMap<>();
        c.put("red", Color.red);
        c.put("blue", Color.blue);
        c.put("green", Color.green);
        c.put("white", Color.white);
        c.put("cyan", Color.cyan);
        c.put("magenta", Color.magenta);
        c.put("pink", Color.pink);
        c.put("yellow", Color.yellow);
        colors = Collections.unmodifiableMap(c);
    }

    public AddCategoryFrame() {
        super();

        this.setEnabled(true);
        this.setVisible(true);
        this.setSize(200, 120);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        this.addButton.addActionListener(e -> {

            String categoryName = this.categoryName.getText();
            String selectedColor = (String) this.colorPicker.getSelectedItem();

            ClippyContext ctx = ClippyContext.getInstance();

            try {
                ctx.getRepository().addCategory(categoryName, colors.get(selectedColor));
                this.setVisible(false);
                this.dispose();
            } catch (InvalidParameterException exception) {
                JOptionPane.showMessageDialog(this, "Category already exists");
            }

            // a note for now, alternate way of closing window with event
            //this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        });
        this.setContentPane(panel);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.setBorder(BorderFactory.createTitledBorder(""));
        final JLabel label1 = new JLabel();
        label1.setEnabled(true);
        label1.setText("Add new category");
        panel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        categoryName = new JTextField();
        panel.add(categoryName, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        addButton = new JButton();
        addButton.setText("Add");
        panel.add(addButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
