package org.oldbox.clippy.frames;

import org.oldbox.clippy.ClippyContext;
import org.oldbox.clippy.NoteEntry;

import javax.swing.*;
import java.awt.*;

public class DatabaseContentFrame extends JFrame {
    private JTextArea textArea1;
    private JPanel panel1;


    private static String getDatabaseDataAsText() {

        ClippyContext ctx = ClippyContext.getInstance();

        StringBuilder data = new StringBuilder();

        for (String categoryName : ctx.getRepository().getCategories()) {
            data.append(categoryName).append("\n");

            for (NoteEntry entry : ctx.getRepository().getCategory(categoryName).getEntries()) {
                data.append(entry.getTimestamp()).append(" ").append(entry.getData()).append("\n");
            }

            data.append("\n");
        }

        return data.toString();
    }

    public DatabaseContentFrame() {

        this.setEnabled(true);
        this.setVisible(true);
        this.setSize(800, 600);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        this.textArea1.setText(getDatabaseDataAsText());

        this.add(panel1);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        textArea1 = new JTextArea();
        textArea1.setEditable(false);
        panel1.add(textArea1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
