package org.oldbox.clippy.frames;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.oldbox.clippy.ClippyContext;
import org.oldbox.clippy.NoteEntry;

import javax.swing.*;
import java.awt.*;
import java.nio.file.FileSystemException;

public class DatabaseContentFrame extends JFrame {
    private JTextArea textArea1;
    private JPanel panel1;


    private static String getDatabaseDataAsText() {

        ClippyContext ctx = ClippyContext.getInstance();

        StringBuilder data = new StringBuilder();

        try {
            for (String categoryName : ctx.getRepository().getCategories()) {
                data.append(categoryName).append("\n").append("\n");

                for (NoteEntry entry : ctx.getRepository().getCategory(categoryName).getEntries()) {
                    data.append(entry.getTimestamp()).append("\n").append(entry.getData()).append("\n\n");
                }

                data.append("--------------").append("\n");
            }
        } catch (FileSystemException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Unable to read from save file");
        }

        return data.toString();
    }

    public DatabaseContentFrame() {

        this.setEnabled(true);
        this.setVisible(true);
        this.setSize(800, 600);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        this.textArea1.setText(getDatabaseDataAsText());

        this.add(panel1);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        textArea1 = new JTextArea();
        textArea1.setEditable(false);
        panel1.add(textArea1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
